#server:
#  port: 8082
#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  datasource:
#    driver-class-name : com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.22.130/guli_wms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: root
#  redis:
#    host: 192.168.22.130
#mybatis-plus:
#  mapper-locations: classpath:mapper/wms/**/*.xml  # 读取映射文件
##  global-config:
##    db-config:
##      id-type: auto  # 默认使用数据库自增